spring:
  datasource:
    generate-unique-name: false
  h2:
    console:
      enabled: true
      path: /h2-console
# disebeling hibernate validations when persisting the entity
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  # configuring Pageable
#  data:
#    web:
#      pageable:
#        page-parameter: currentPage
#        size-parameter: pageSize
